### ISSUE TITLE
Dependency of future

### ISSUE THREAD

**Issue by frenzymadness** [theojulienne/PySignals#7]
Hello. I see that the project depends on future. I can find only a single usage of it in the codebase.
https://github.com/theojulienne/PySignals/blob/832b2c6733fd8e25dcfa893c8b9929e13e7c6352/pysignals/dispatcher.py#L6
Do you think it's still useful? I'm asking because future is broken with the latest Python 3.12 and will be even more with 3.13 so it might be a good idea to get rid of it.

**Comment by knight-of-ni** [comment]
It's been a while since I've looked at the codebase, but you're right it looks like pysignals just uses the range function one time. 
I'm not opposed to rewriting this.

However, have you contacted the authors of the python-future project to determine when they plan to resolve the issue?

It looks like this is a known issue and indeed there is even a PR to fix, at least one problem, with python 3.12:
https://github.com/PythonCharmers/python-future/issues/618

What environment are you working in?

I can see in Fedora that python-future has been patched (from the PR in the previous link) and is building fine for that distro:
https://src.fedoraproject.org/rpms/future/blob/rawhide/f/future.spec#_36

**Comment by frenzymadness** [comment]
You are right, we've managed (in Fedora) to patch the sources and also create a new Python package called zombie-imp which contains the imp module removed from the standard library to make the future package work with Python 3.12. However, the plan for 3.13 is to also remove lib2to3 from the standard library, which is I'd say the core of future and I'd rather remove the dependency on future in projects where it's possible and doesn't mean a lot of work rather than fix the old library.
Moreover, many packages have future in the list of dependencies even if they do not use it at all or they use one little thing from it and it's simple to rewrite even without dropping Python 2 support.

**Comment by frenzymadness** [comment]
And it!s already removed: https://github.com/python/cpython/issues/104780

**Comment by knight-of-ni** [comment]
Understood. Thank you for the explanation. 

I'll get this fixed in this upstream repo then build a new pysignals package in Fedora repos.

**Comment by knight-of-ni** [comment]
Because we are using range in a For loop, it turns out this project didn't even need python-future at all. The native behavior of range in python 2 or 3 will work just fine.
